# Copyright (C) 2026 アケネＪ / Akenejie
# SPDX-License-Identifier: AGPL-3.0-only
#
# Overte Headless-Server (overte-hs) version header generator.
#
# version.txt at the repository root is the single source of truth for the
# overte-hs release version: the release pipeline (GitHub Actions) reads it for
# tags/binaries and this script turns it into a C header so `--version` reports
# the same number. Bumping the version means editing version.txt only.
#
# Usage: cmake -DSRC=<abs version.txt> -DOUT=<abs header.hpp> -P .../GenerateVersionHeader.cmake

if (NOT DEFINED SRC OR NOT DEFINED OUT)
    message(FATAL_ERROR "Usage: cmake -DSRC=<version.txt> -DOUT=<header.hpp> -P GenerateVersionHeader.cmake")
endif()

file(STRINGS "${SRC}" OVERTE_HS_VERSION LIMIT_COUNT 1)
string(STRIP "${OVERTE_HS_VERSION}" OVERTE_HS_VERSION)
if (NOT OVERTE_HS_VERSION)
    message(FATAL_ERROR "version.txt is empty: ${SRC}")
endif()

set(OVERTE_HS_VERSION_HPP "// Auto-generated by cmake/GenerateVersionHeader.cmake. DO NOT EDIT.\n")
string(APPEND OVERTE_HS_VERSION_HPP "// Source of truth: version.txt at the repository root.\n")
string(APPEND OVERTE_HS_VERSION_HPP "#pragma once\n\n")
string(APPEND OVERTE_HS_VERSION_HPP "#define OVERTE_HS_VERSION \"${OVERTE_HS_VERSION}\"\n")

file(WRITE "${OUT}" "${OVERTE_HS_VERSION_HPP}")