#
# Copyright (C) 2026 アケネＪ / Akenejie
# SPDX-License-Identifier: AGPL-3.0-only
# (Full AGPL text in LICENSE-AGPL-3.0.txt; see NOTICE in the repository root)
#
# GenerateDefaultData.cmake - a configure/script-time generator that turns the
# default room (entities/models.json.gz + assets/files/* + assets/map.json) into
# C byte-array declarations. This keeps the single-binary launcher free of Qt
# resource dependencies and of any runtime data files, while still being able
# to seed a freshly created --data directory at first run.
#
# Usage:
#   cmake -DENTITY_SRC=<models.json.gz> -DMAP_SRC=<map.json>
#         -DFILES_DIR=<assets/files dir> -DOUT=<output header>
#         -P GenerateDefaultData.cmake

if(NOT DEFINED ENTITY_SRC OR NOT DEFINED MAP_SRC OR NOT DEFINED FILES_DIR OR NOT DEFINED OUT)
  message(FATAL_ERROR
    "usage: cmake -DENTITY_SRC=<models.json.gz> -DMAP_SRC=<map.json> "
    "-DFILES_DIR=<assets/files dir> -DOUT=<output header> "
    "-P ${CMAKE_CURRENT_LIST_FILE}")
endif()

if(NOT EXISTS "${ENTITY_SRC}" OR NOT EXISTS "${MAP_SRC}" OR NOT EXISTS "${FILES_DIR}")
  message(FATAL_ERROR "GenerateDefaultData.cmake: ENTITY_SRC/MAP_SRC/FILES_DIR must exist")
endif()

file(GLOB _asset_files "${FILES_DIR}/*")
list(SORT _asset_files)

set(_out
  "// Generated by cmake/GenerateDefaultData.cmake.\n"
  "// The default room: entity persist file (entities/models.json.gz) and the\n"
  "// asset-server content (assets/files/* + assets/map.json) it references,\n"
  "// embedded so a freshly created --data dir can be seeded at first run.\n")

# Entity persist file (default empty/builder-grid room).
file(READ "${ENTITY_SRC}" _entities_hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _entities_bytes "${_entities_hex}")
string(LENGTH "${_entities_hex}" _entities_hex_len)
math(EXPR _entities_size "${_entities_hex_len} / 2")
string(APPEND _out "static const unsigned char gDefaultModelsJsonGz[] = { ${_entities_bytes} };\n")
string(APPEND _out "static const size_t gDefaultModelsJsonGzSize = ${_entities_size};\n\n")

# Asset-server map file (path -> hash mappings).
file(READ "${MAP_SRC}" _map_hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _map_bytes "${_map_hex}")
string(LENGTH "${_map_hex}" _map_hex_len)
math(EXPR _map_size "${_map_hex_len} / 2")
string(APPEND _out "static const unsigned char gDefaultAssetMapJson[] = { ${_map_bytes} };\n")
string(APPEND _out "static const size_t gDefaultAssetMapJsonSize = ${_map_size};\n\n")

# One asset-server data file per sha256-named file in assets/files.
string(APPEND _out "typedef struct DefaultDataAsset {\n")
string(APPEND _out "    const char* fileName;\n")
string(APPEND _out "    const unsigned char* data;\n")
string(APPEND _out "    size_t size;\n")
string(APPEND _out "} DefaultDataAsset;\n\n")

set(_asset_count 0)
set(_asset_table "static const DefaultDataAsset gDefaultAssets[] = {\n")
foreach(_file IN LISTS _asset_files)
  get_filename_component(_name "${_file}" NAME)
  file(READ "${_file}" _hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
  string(LENGTH "${_hex}" _hex_len)
  math(EXPR _size "${_hex_len} / 2")
  string(APPEND _out "static const unsigned char gDefaultAsset_${_name}[] = { ${_bytes} };\n")
  string(APPEND _asset_table "    { \"${_name}\", gDefaultAsset_${_name}, ${_size} },\n")
  math(EXPR _asset_count "${_asset_count} + 1")
endforeach()
string(APPEND _out "\n${_asset_table}};\n")
string(APPEND _out "static const size_t gDefaultAssetsCount = ${_asset_count};\n")

file(WRITE "${OUT}" "${_out}")