#
# Copyright (C) 2026 アケネＪ / Akenejie
# SPDX-License-Identifier: AGPL-3.0-only
# (Full AGPL text in LICENSE-AGPL-3.0.txt; see NOTICE in the repository root)
#
# GenerateDefaultData.cmake - a configure/script-time generator that turns a
# small binary asset (the default empty world, entities/models.json.gz) into a
# C byte-array header. This keeps the single-binary launcher free of Qt
# resource dependencies and of any runtime data files, while still being able
# to seed a freshly created --data directory with an empty-but-valid room.
#
# Usage: cmake -DSRC=<input binary> -DOUT=<output header> -P GenerateDefaultData.cmake

if(NOT DEFINED SRC OR NOT DEFINED OUT)
  message(FATAL_ERROR "usage: cmake -DSRC=<input binary> -DOUT=<output header> -P ${CMAKE_CURRENT_LIST_FILE}")
endif()

file(READ "${SRC}" _default_data_hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _default_data_bytes "${_default_data_hex}")
string(LENGTH "${_default_data_hex}" _default_data_hex_len)
math(EXPR _default_data_size "${_default_data_hex_len} / 2")

file(WRITE "${OUT}"
"// Generated by cmake/GenerateDefaultData.cmake from ${SRC}.
// The default empty world, embedded so a freshly created --data dir can be
// seeded with an empty-but-valid entity persist file at first run.
static const unsigned char gDefaultModelsJsonGz[] = {
    ${_default_data_bytes}
};
static const size_t gDefaultModelsJsonGzSize = ${_default_data_size};
")